// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6n3ZJQ56lfR9FGwVp8U5NCrI1R-cDY3s',
    appId: '1:421593150176:web:bd57e6e92dca7eb4a51685',
    messagingSenderId: '421593150176',
    projectId: 'notey-31ea9',
    authDomain: 'notey-31ea9.firebaseapp.com',
    storageBucket: 'notey-31ea9.firebasestorage.app',
    measurementId: 'G-7VH8K6GWR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX50gP2MaGmxwu9lw7CGCpdrVmFWbhN_o',
    appId: '1:421593150176:android:39bb5677f7a6dd89a51685',
    messagingSenderId: '421593150176',
    projectId: 'notey-31ea9',
    storageBucket: 'notey-31ea9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_aLV0wJHrJfwMIWIB2FcB6qN045oIreo',
    appId: '1:421593150176:ios:943ee94b1288eae4a51685',
    messagingSenderId: '421593150176',
    projectId: 'notey-31ea9',
    storageBucket: 'notey-31ea9.firebasestorage.app',
    iosClientId: '421593150176-fj6hgm8079ifq4hpqa2qi85kk78q99aq.apps.googleusercontent.com',
    iosBundleId: 'com.example.notey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_aLV0wJHrJfwMIWIB2FcB6qN045oIreo',
    appId: '1:421593150176:ios:943ee94b1288eae4a51685',
    messagingSenderId: '421593150176',
    projectId: 'notey-31ea9',
    storageBucket: 'notey-31ea9.firebasestorage.app',
    iosClientId: '421593150176-fj6hgm8079ifq4hpqa2qi85kk78q99aq.apps.googleusercontent.com',
    iosBundleId: 'com.example.notey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6n3ZJQ56lfR9FGwVp8U5NCrI1R-cDY3s',
    appId: '1:421593150176:web:870a2d5d4cbe6da9a51685',
    messagingSenderId: '421593150176',
    projectId: 'notey-31ea9',
    authDomain: 'notey-31ea9.firebaseapp.com',
    storageBucket: 'notey-31ea9.firebasestorage.app',
    measurementId: 'G-G0MJZL1T31',
  );
}
